# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
