# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergen_types', '0001_initial'),
        ('patients', '0002_auto_20161122_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='analyzes',
            field=models.ManyToManyField(to='allergen_types.AllergenType'),
        ),
    ]
